# Windows Dockerfile (Windows Server 2019) for PySide2 build
ARG REPO=mcr.microsoft.com/dotnet/framework/runtime
FROM $REPO:4.8-20230808-windowsservercore-ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install Qt
ARG QT_EMAIL
ARG QT_PASSWORD
RUN $exePath = "$env:TEMP + '\qt-unified-windows-x64-4.4.1-online.exe'" ; \ 
    curl.exe -L 'https://download.qt.io/archive/online_installers/4.4/qt-unified-windows-x64-4.4.1-online.exe' --output "$exePath" ; \
    cmd /C "$exePath" install qt.qt5.5152.qtwebengine qt.qt5.5152.qtscript qt.qt5.5152.win64_msvc2019_64 \ 
        qt.qt5.5152.qtwebglplugin.win64_msvc2019_64 qt.qt5.5152.qtwebengine.win64_msvc2019_64 qt.qt5.5152.qtvirtualkeyboard.win64_msvc2019_64 \
        qt.qt5.5152.qtscript.win64_msvc2019_64 qt.qt5.5152.qtquicktimeline.win64_msvc2019_64 qt.qt5.5152.qtquick3d.win64_msvc2019_64 \
        qt.qt5.5152.qtpurchasing.win64_msvc2019_64 qt.qt5.5152.qtnetworkauth.win64_msvc2019_64 qt.qt5.5152.qtlottie.win64_msvc2019_64 \
        qt.qt5.5152.qtdatavis3d.win64_msvc2019_64 qt.qt5.5152.qtcharts.win64_msvc2019_64 qt.qt5.5152.debug_info.win64_msvc2019_64 \
        --root C:\Qt --auto-answer telemetry-question=No,AssociateCommonFiletypes=Yes --accept-licenses --accept-obligations \ 
        --email "$env:QT_EMAIL" --pw "$env:QT_PASSWORD" --confirm-command --accept-messages --filter-packages "DisplayName=Qt 5.15.2"


# Install Chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# Install Python 3.12, CMake, Ninja, and 7-Zip via Chocolatey
RUN choco install -y python --version 3.12.3; \
    choco install -y cmake --version=3.31.11 --installargs 'ADD_CMAKE_TO_PATH=System'; \
    choco install -y ninja; \
    choco install -y git; \
    choco install -y 7zip; \
    choco install -y llvm --version 14.0.6

# Install MSVC Build Tools 2019 via Chocolatey
RUN choco install -y visualstudio2019buildtools --version 16.11.3; \
    choco install -y visualstudio2019-workload-vctools --version 1.0.1

# Set Environment Variables
ENV CLANG_INSTALL_DIR="C:\Program Files\LLVM"
RUN [Environment]::SetEnvironmentVariable('PATH', 'C:\Qt\5.15.2\msvc2019_64\bin;C:\Program Files\LLVM\bin;C:\Program Files\CMake\bin;C:\Python312;C:\Python312\Scripts;' + $env:PATH, [EnvironmentVariableTarget]::Machine)

WORKDIR C:/app

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

RUN git config --global --add safe.directory '*'
CMD ["powershell"]
